/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as CliRouteImport } from './routes/cli'
import { Route as DetectionsRouteImport } from './routes/detections'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as PackageRouteImport } from './routes/package'
import { Route as PolicyRouteImport } from './routes/policy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsRoute = DetectionsRouteImport.update({
  id: '/detections',
  path: '/detections',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageRoute = PackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/cli': typeof CliRoute
  '/detections': typeof DetectionsRoute
  '/matrix': typeof MatrixRoute
  '/package': typeof PackageRoute
  '/policy': typeof PolicyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/cli': typeof CliRoute
  '/detections': typeof DetectionsRoute
  '/matrix': typeof MatrixRoute
  '/package': typeof PackageRoute
  '/policy': typeof PolicyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/cli': typeof CliRoute
  '/detections': typeof DetectionsRoute
  '/matrix': typeof MatrixRoute
  '/package': typeof PackageRoute
  '/policy': typeof PolicyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/cli'
    | '/detections'
    | '/matrix'
    | '/package'
    | '/policy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaign'
    | '/cli'
    | '/detections'
    | '/matrix'
    | '/package'
    | '/policy'
  id:
    | '__root__'
    | '/'
    | '/campaign'
    | '/cli'
    | '/detections'
    | '/matrix'
    | '/package'
    | '/policy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRoute: typeof CampaignRoute
  CliRoute: typeof CliRoute
  DetectionsRoute: typeof DetectionsRoute
  MatrixRoute: typeof MatrixRoute
  PackageRoute: typeof PackageRoute
  PolicyRoute: typeof PolicyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections': {
      id: '/detections'
      path: '/detections'
      fullPath: '/detections'
      preLoaderRoute: typeof DetectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package': {
      id: '/package'
      path: '/package'
      fullPath: '/package'
      preLoaderRoute: typeof PackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRoute: CampaignRoute,
  CliRoute: CliRoute,
  DetectionsRoute: DetectionsRoute,
  MatrixRoute: MatrixRoute,
  PackageRoute: PackageRoute,
  PolicyRoute: PolicyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
